spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:projeto
security:
  oauth2:
    resource:
      id: bcrypt
#    client:
#      registration:
#        client-id: client
#        client-secret: 123
#        scope: password

logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR

server:
  port: 5000