spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:projeto
security:
  oauth2:
    resource:
      id: bcrypt

logging:
  level:
    root: INFO
    org.hibernate: ERROR

server:
  port: 5000